services:
  node1:
    container_name: node1
    hostname: node1
    build: ./docker/db
    volumes:
      - ./docker/db/conf/node1.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: root
    command: --wsrep-new-cluster
  node2:
    container_name: node2
    hostname: node2
    build: ./docker/db
    volumes:
      - ./docker/db/conf/node2.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: root
    depends_on:
      - node1
  node3:
    container_name: node3
    hostname: node3
    build: ./docker/db
    volumes:
      - ./docker/db/conf/node3.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: root
    depends_on:
      - node1
      - node2