services:
  # MariaDB Galera Cluster
  node1:
    container_name: node1
    hostname: node1
    build: ./docker/db
    volumes:
      - ./docker/db/conf/node1.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/initdb.d:/docker-entrypoint-initdb.d
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: root
    command: --wsrep-new-cluster
  node2:
    container_name: node2
    hostname: node2
    build: ./docker/db
    volumes:
      - ./docker/db/conf/node2.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: root
    depends_on:
      - node1
  node3:
    container_name: node3
    hostname: node3
    build: ./docker/db
    volumes:
      - ./docker/db/conf/node3.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: root
    depends_on:
      - node1
      - node2

  # ProxySQL Cluster
  proxysql1:
    container_name: proxysql1
    hostname: proxysql1
    build: ./docker/proxysql
    volumes:
      - ./docker/proxysql/conf/proxysql.cnf:/etc/proxysql.cnf
    depends_on:
      - node1
      - node2
      - node3
  proxysql2:
    container_name: proxysql2
    hostname: proxysql2
    build: ./docker/proxysql
    volumes:
      - ./docker/proxysql/conf/proxysql.cnf:/etc/proxysql.cnf
    depends_on:
      - node1
      - node2
      - node3
      - proxysql1
  proxysql3:
    container_name: proxysql3
    hostname: proxysql3
    build: ./docker/proxysql
    volumes:
      - ./docker/proxysql/conf/proxysql.cnf:/etc/proxysql.cnf
    depends_on:
      - node1
      - node2
      - node3
      - proxysql1
      - proxysql2

  # HAProxy
  haproxy:
    container_name: haproxy
    hostname: haproxy
    build: ./docker/haproxy
    volumes:
      - ./docker/haproxy/conf/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    depends_on:
      - proxysql1
      - proxysql2
      - proxysql3
    ports:
      - 6033:6033
      - 8404:8404
