-- ProxySQL user
CREATE USER IF NOT EXISTS 'monitor'@'%' IDENTIFIED BY 'monitor' with MAX_USER_CONNECTIONS 9;
GRANT USAGE, PROCESS, REPLICATION CLIENT,SLAVE MONITOR, SELECT ON *.* TO 'monitor'@'%';

--- Exporter user
CREATE USER IF NOT EXISTS 'exporter'@'%' IDENTIFIED BY 'exporter' WITH MAX_USER_CONNECTIONS 9;
GRANT USAGE, PROCESS, REPLICATION CLIENT, SLAVE MONITOR, SELECT ON *.* TO 'exporter'@'%';