{
 "title": "Local Galera Cluster Monitoring Dasboards",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "proxysql_instance",
    "query": {
     "query": "label_values(proxysql_uptime_seconds_total,instance)"
    }
   },
   {
    "name": "proxysql_endpoint",
    "query": {
     "query": "label_values(proxysql_connpool_conns,endpoint)"
    }
   },
   {
    "name": "mysqld_exporter_instance",
    "query": {
     "query": "label_values({instance=~\"node1:9104|node2:9104|node3:9104\"},instance)"
    }
   },
   {
    "name": "node_exporter_instance",
    "query": {
     "query": "label_values({instance=~\"node1:9100|node2:9100|node3:9100\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Galera Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Galera Cluster Size",
   "type": "gauge",
   "description": "Size of Galera Cluster Size",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_status_wsrep_cluster_size{instance=~\"$mysqld_exporter_instance\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Cluster Node Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "proxysql_connpool_conns_status{instance=~\"$proxysql_instance\", endpoint=~\"$proxysql_endpoint\"}",
     "legendFormat": "HG {{hostgroup}}={{endpoint}}"
    }
   ]
  },
  {
   "title": "Flow Control",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(mysql_global_status_wsrep_flow_control_sent[10m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MariaDB",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "sum by(instance) (rate(node_cpu_seconds_total{mode!=\"idle\", instance=~\"$node_exporter_instance\"}[$__rate_interval])) * 100",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "targets": [
      {
       "expr": "100 * (node_memory_MemTotal_bytes{instance=~\"$node_exporter_instance\"} - node_memory_MemAvailable_bytes{instance=~\"$node_exporter_instance\"}) / node_memory_MemTotal_bytes{instance=~\"$node_exporter_instance\"}",
       "legendFormat": "{{job}}"
      }
     ]
    }
   ]
  },
  {
   "title": "ProxySQL Cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "ProxySQL Cluster Size",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count_values(\"count\", proxysql_server_connections_total{instance=~\"$proxysql_instance\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}